### ISSUE TITLE
sendOffer not defined

### ISSUE THREAD

**Issue by itsjustacayman** [Jack-Flux/node-opskins-trade#10]
https://gyazo.com/300fcbebcb343be5a55a3f988f40595f

const opskinsTrade = require('node-opskins-trade');

const tradeManager = new opskinsTrade('key', 'twoFactor');

function sendToBot(offer){
	if(offer.withdraw){
		tradeManager.sendOffer(offer.steamId, offer.items);
		return;
	}else{
		success("Sent trade offer: " + offer.steamId + " items; " + offer.items);
		tradeManager.sendOffer(offer.steamId, offer.items);
		return;
	}
}

**Comment by Jack-Flux** [comment]
Most likely your key or twoFactor are incorrect.
